"""Replay buffer for self-play training data.

Stores (state, policy, outcome) examples generated by self-play games and
supports random-sampling training batches. Bounded capacity, oldest evicted
first, so memory doesn't grow without limit over a long training run.
"""

from collections import deque
from dataclasses import dataclass

import numpy as np
import torch as T
from numpy.typing import NDArray


@dataclass(frozen=True)
class Example:
    """One self-play training example.

    Attributes:
        state: (3, 17, 17) board tensor -- from_state()'s output with the
            batch dimension squeezed out.
        policy: (action_space.NUM_ACTIONS,) MCTS visit-count distribution
            over the fixed action space.
        outcome: The eventual game result from this position's own current
            mover's perspective, in [-1, 1] -- the same convention
            heuristic.potential and SternhalmaZero's value head use.
    """

    state: T.Tensor
    policy: NDArray[np.float32]
    outcome: float


class ReplayBuffer:
    """Bounded FIFO buffer of self-play training examples."""

    def __init__(self, capacity: int) -> None:
        self._examples: deque[Example] = deque(maxlen=capacity)

    def __len__(self) -> int:
        return len(self._examples)

    def push(self, example: Example) -> None:
        self._examples.append(example)

    def sample(self, batch_size: int) -> list[Example]:
        """A random batch of `batch_size` examples, without replacement.

        Raises ValueError if the buffer holds fewer than `batch_size`
        examples.
        """
        if batch_size > len(self._examples):
            raise ValueError(
                f"Cannot sample {batch_size} examples from a buffer of "
                f"{len(self._examples)}"
            )
        indices = np.random.choice(
            len(self._examples), size=batch_size, replace=False
        )
        return [self._examples[int(i)] for i in indices]
