[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sternhalma-agent"
version = "0.1.0"
description = "Sternhalma agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["cbor2", "numpy", "scipy", "scikit-learn", "torch", "sternhalma-rs"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.uv.sources]
sternhalma-rs = { path = "../sternhalma-python", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["src/sternhalma_agent"]

[tool.pytest.ini_options]
pythonpath = ["."]
